### ISSUE TITLE
Tracks 2.4.1 installation documentation incomplete

### ISSUE THREAD

**Issue by coridonhenshaw** [TracksApp/tracks#2372] opened 2020-04-13 19:44 UTC
I recently downloaded Tracks 2.4.1 from https://www.getontracks.org/ with the intention of self-hosting Tracks on Linux. However, I was unable to install it because the installation instructions in doc/installation.md are grossly incomplete and various scripts used during the installation are not functional.

These are the problems I encountered before concluding that the current release of Tracks is broken and unusable:

1. The instructions do not mention the raft of dependencies needed to install Ruby on Rails, including GCC, GCC-C++, zlib-devl, and libmysqlclient/libmariadb-devel. The Ruby install process gives unhelpful error messages; discovering the required components involved repeatedly digging through logs and stackoverflow. The fact that this is not documented is user hostile behavior.

2. The instructions do not mention that _bundle update --bundler_ must be run after installing Ruby otherwise _bundle install_ will fail because the Ruby stack will be unable to find the right version of bundler otherwise. The fact that this is not documented is user hostile behavior.

3. The instructions do not mention that _bundle exec rails server -e production_ will recreate the entire MySQL and Ruby on Rails stacks in a Docker container, **which makes the entire process above, and the hours it took to work around the undocumented pitfalls, a completely pointless waste of time, bandwidth and disk space. This is incredibly user hostile behavior.**

4. The instructions do not mention that _bundle exec rails server -e production_ will fail to expose port :3000 inside the docker container to the host network stack unless _BIND_DOCKER_SERVICE_PORTS=1_ is already exported. The fact that this is not documented is user hostile behavior.

5. _bundle exec rails server -e production_ ignores the directive to start in production mode and will only run in development mode. This is a bug.

6. Because the current version of Tracks uses its own Dockerized MySQL database, the step in doc/installation.md to initialize the database (_bundle exec rake db:migrate RAILS_ENV=production_) is pointless. Tracks-in-Docker does not access the external database created by this step. This is a completely pointless waste of time, bandwidth and disk space.

7. The dockerized MySQL database is never initialized, meaning that all attempts to access the Tracks installation via a browser fail with either "We're sorry, but something went wrong" or an ActiveRecord::PendingMigrationError. **This is a bug and makes Tracks unusable.**

Working installers or installation instructions are vital, because without them no one can use your code. Respect for your potential users is also vital, and **it is incredibly disrespectful to the open source community to release something this broken that wastes so much of a potential user's time and effort to no benefit whatsoever.**

**Comment by ZeiP** [comment] 2020-04-14 09:34
Thanks for the feedback. There's indeed been some changes to the installation process and because of them the documentation is probably still a bit outdated. There are some other issues linking to this one, namely #2297 and #2170.

Sorry for your experience regarding the installation. However, it's good to realise that Tracks, as almost all other OSS solutions, are made by a volunteer basis and therefore it's important to stay constructive in the community. While I agree that the documentation should definitely be better and will most certainly be enhanced, I do think that it's equally useful to release a software even if there's no installer – that way people that have more experience with the technology, in this case Ruby on Rails, can make use of the software despite the somewhat more difficult installation process.

The software is a community-driven effort, so if you have concrete suggestions to enhance the installation documentation, feel free to make a pull request. If not, I'll try to find some time to make the documentation better – I'm currently not using the latest environment myself, as that's something @mattr- has created, but it would be useful to figure that out myself and perhaps fix the documentation in the process.

Again, thanks for the feedback, it's important for us all to realise that the installation process isn't quite as easy as it should be.

**Comment by phlummox** [comment] 2020-07-15 13:36
A Docker instance on Docker hub, containing a minimal setup of Tracks which works ***out of the box***, might be a good start - then, even if the documentation is out of date, potential users can look at the Dockerfile and at least see an example of a working configuration.

I'd also get rid of the literal dozens of "install" pages sitting under <https://github.com/TracksApp/tracks/wiki/Installation> - I suspect most of those are conflicting and/or out of date, and it would be better to have *one* set of instructions that works on at least *one* platform than, say, twenty that don't work on any platform.

Anyway. So far as I can work out, if running on an Ubuntu 16.04 system, the steps needed in the Dockerfile are roughly:

- Get a more up-to-date version of ruby, plus all the prerequisites:
  ```
  $ echo | sudo add-apt-repository ppa:brightbox/ruby-ng`
  $ sudo apt-get update
  $ sudo apt-get install -y --no-install-recommends ruby2.6  ruby2.6-dev build-essential sqlite3 libsqlite3-dev zlib1g-dev libtinfo-dev libgmp-dev libxml2-dev pkg-config libssl-dev
  ```
  (some of these packages are probably not necessary, I just installed everything mentioned in build error messages, plus a few more just in case)
- `sudo apt-get install tzdata`
- Set the timezone. Outside of Docker, one uses `sudo dpkg-reconfigure tzdata`; inside, I think you can probably just write, say, "Australia/Sydney" to the file `/etc/timezone`
- `export PATH=$HOME/.gem/ruby/2.6.0/bin:$PATH`
- `gem install --user-install rubygems-update bundler` \
  (not sure if both these are necessary, but I updated `rubygems-update` to be on the safe side)
- `bundle install --without development test mysql`
- **\*ADD WORKING CONFIG FILES HERE\*** [Supply a sample `database.yml` and `site.yml` config file, set up to use Sqlite, and with minimal security - this is just a demo to run on the local host]
- `bundle exec rake db:migrate RAILS_ENV=production`
- `bundle exec rake assets:precompile RAILS_ENV=production`
- `export RAILS_ENV=production` \
  (Because we're running inside Docker already, and, ridiculously, the startup script attempts to run `docker-compose` - without this ever being mentioned as a prerequisite - unless this env var is set. Putting the env var at random points in the `bundle` command-line invocation doesn't seem to help.)
- `bundle exec rails server -e production -p 8080` [or some other port. But 8080 is common for demo web apps, and it's good to show how the port is set].
- **??? \*MYSTERY STEPS GO HERE\*.** Apparently, some additional setup is needed at this point, because trying to register an admin user just results in a "We're sorry, but something went wrong" error, as noted previously.

The Docker configuration *currently* available for Tracks on the Docker hub does not at all work "out of the box", so doesn't serve the purpose I've outlined. To be honest, I'm not at all sure what it *does* do, but whatever it is, working "out of the box" is not it - I presume it's there just for Tracks developers.

Given that I've outlined a majority of the steps for you, and given that the Tracks developers presumably do know how to get it running, I imagine it should be a fairly quick task for someone to turn this into a working Docker instance.

I look forward to seeing it :)

As an aside, the waste of people's time you're causing by not having working installation instructions is certainly very irritating, though I'd not go so far as saying, in boldface type, that it's "**incredibly disrespectful to the open source community**". I'd settle for just "*mildly* disrespectful" - I've had far worse affronts to my respect than this on the Internet.

**Comment by ZeiP** [comment] 2020-07-16 18:10
You're quite right. I actually just created an organisation in Docker Hub for future use, hopefully we'll / I'll be able to create a ready-for-use Docker image.
I'm currently using an install without Docker myself, but as I took over the project today I'll try to figure out the Docker side of things pretty soon.
Basically it seems that your instance is missing the stylesheets – with those it would probably look much more like it should.

**Comment by ZeiP** [comment] 2020-07-16 21:36
Not sure how the original Docker configuration should've worked, but I changed the configuration so that it should now work at least preliminarily. The exact steps are listed in https://github.com/TracksApp/tracks/wiki/Docker-image

**Comment by ZeiP** [comment] 2020-07-19 22:12
There are now better installation instructions for the master branch in https://github.com/TracksApp/tracks/blob/master/doc/installation.md. I'm planning on releasing a new version after getting at least the library updates in, but it'd be awesome to have some feedback before the release.

I shifted the logic so that now you don't need to add the .skip-docker file (although it doesn't certainly harm any), but if you want to run commands and have them being run inside the Docker Compose installation you need to create a .use-docker file similarly.

There are updated instructions for using the Docker machines in the doc directory: https://github.com/TracksApp/tracks/blob/master/doc/installation.md  Let me know if you encounter any problems with them by posting a new issue. Thanks!

**Comment by rharmonson** [comment] 2020-07-23 04:18
@ZeiP et al,

I do not understand the fascination folks have with Docker, but as long as other installation scenarios are provided--I saw you  provided [Custom server installation](https://github.com/TracksApp/tracks/blob/master/doc/installation.md#custom-server-installation), Docker-phobes like me won't run away.

:)

Since I am stuck at home, I can contribute. Is there a desire or value to author distribution specific installation documentation? If true, what platforms?

I just reviewed my [Installing Tracks 2.2.2 on CentOS 6.5 Minimal x86_64 ](https://github.com/TracksApp/tracks/wiki/Installing-Tracks-2.2.2-on-CentOS-6.5-Minimal-x86_64) documentation from 2015. Wow! How time flies.

**Comment by ZeiP** [comment] 2020-07-23 08:59
The most important benefit to Docker, IMO, is that it makes it easy to create the same kind of environment everyone else using Tthe same software has – and as an additional bonus provides a bit of isolation and thus security for the application, whether in development or production. (The new Docker image is also supported in production use, which wasn't the case with the old one.)

Custom installations with their varying libraries and paths and whatnot tend to be a bit tricky and are certainly harder to support. Therefore a user making a custom installation has to do a bit more work themselves to figure out the correct packages and make things work, but I certainly don't want to force anyone to use Docker – until quite recently I, too, preferred custom installation over Docker, and just migrated my own installation to Docker a few days ago :)

I think it would be very useful to test the custom installation process in https://github.com/TracksApp/tracks/blob/master/doc/installation.md#custom-server-installation and make any amendments via PR or report any issues here – I didn't test it very thoroughly, only made the required changes that I knew of. Doing that you could probably make more detailed installation instructions for Debian (or some other similar distribution) and/or CentOS (or some similar distribution), which would both be very beneficial. If we had the instructions for both those major distribution types, we'd be fairly well off and anyone willing to make a custom installation could apply those as needed in their exact environment.

**Comment by ZeiP** [comment] 2020-07-24 10:39
Just checked the original issue description. Here are the comments to the issues raised therein.

1. The custom installation is not the suggested method for installing the software and requires more knowledge from the user. The installation instructions were pretty limited regarding Docker, that has now been fixed. Normal dependencies or problems with Ruby installation are out of scope for this project.

5. I'm not sure where you ran the command, so I couldn't reproduce the problem. If the problem persist, please open a new issue for it.

2., 3., 4., 6., 7. The installation instructions have been revamped, so these should be fixed.

It seems that all the problems should now be fixed, so closing the issue. Feel free to open a new issue for any problems you encounter.

**Closed by ZeiP** 2020-07-24 10:39 UTC
Labels: Documentation, help wanted
