### ISSUE TITLE
Flash of hidden content during recurring_todos page load

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#1980] opened 2016-01-31 21:44 UTC
When loading the recurring_todos page, the form briefly appears on the page before being hidden:
<img width="1476" alt="screen shot 2016-01-31 at 4 42 40 pm" src="https://cloud.githubusercontent.com/assets/1084619/12705156/c7fbcec0-c839-11e5-993e-dc6898fbbab1.png">

**Comment by mattr-** [comment] 2016-02-01 00:57
Yes, I've seen this before but I've been ignoring it for now since that's probably the next thing I'll tackle on my bootstrap UI task list, unless I decide to tackle one of the larger things.

**Comment by mattr-** [comment] 2018-08-05 16:32
Closing since it's not reproducible. Thanks for checking that out @bulletkid!

**Closed by mattr-** 2018-08-05 16:32 UTC
