### ISSUE TITLE
REST API doesn't filter by project

### ISSUE THREAD

**Issue by RedNifre** [TracksApp/tracks#2032] opened 2016-07-17 20:48 UTC
projects/ID/todos.xml returns all todos instead of only the todos of the specified project.

Contexts have the same problem, see https://github.com/TracksApp/tracks/issues/1931

**Comment by C-Otto** [comment] 2016-07-17 20:50
Duplicate of #1726 I guess, please have a look at #2016 for a possible fix.

**Comment by RedNifre** [comment] 2016-07-17 21:18
I interpreted the fix in #2016 to mean this, is this correct?:

projects/ID/todos.xml?limit_to_active_todos=1

Doing it like this hides todos of other projects, but it also limits the response to active todos, obviously. However, as a work-around it's fine for me for now, since I just noticed that all todos of a project are contained in projects/ID.xml

**Comment by ZeiP** [comment] 2019-05-04 19:50
I added a PR #2210 with a fix for this.

**Comment by ZeiP** [comment] 2019-05-20 16:00
Fixed.

**Closed by ZeiP** 2019-05-20 16:00 UTC
