### ISSUE TITLE
Unable to create todo's in tracks 2.3.0

### ISSUE THREAD

**Issue by muianelson** [TracksApp/tracks#1988] opened 2016-02-10 13:44 UTC
I, [2016-02-10T16:37:18.392713 #1852]  INFO -- : Started POST "/tracks/todos" for 127.0.0.1 at 2016-02-10 16:37:18 +0300
I, [2016-02-10T16:37:18.392713 #1852]  INFO -- : Processing by TodosController#create as JS
I, [2016-02-10T16:37:18.392713 #1852]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"sZVUICAn4uV8NuSP5sjv2MtrnU6duO08oyeEG5P4468=", "default_project_name"=>"", "default_context_name"=>"Network and Infrastructure", "new_todo_starred"=>"false", "todo"=>{"description"=>"documentation of network redesign", "notes"=>"documentation", "due"=>"18/02/2016", "show_from"=>"11/02/2016"}, "project_name"=>"Network redesign", "context_name"=>"Network and Infrastructure", "initial_tag_list"=>"", "tag_list"=>"network redesign", "predecessor_input"=>"", "predecessor_list"=>"", "_source_view"=>"todo", "_group_view_by"=>"context", "_tag_name"=>""}
I, [2016-02-10T16:37:18.408338 #1852]  INFO -- : Completed 500 Internal Server Error in 16ms (ActiveRecord: 0.0ms)
F, [2016-02-10T16:37:18.408338 #1852] FATAL -- : 
ArgumentError (bad value for range):
  lib/tracks/utils.rb:39:in `textile'
  lib/tracks/utils.rb:26:in `render_text'
  app/models/todo.rb:382:in `render_note'
  app/controllers/todos_controller.rb:97:in `create'

**Comment by C-Otto** [comment] 2016-02-10 14:04
Does it work to create the todo without a note? Does it work to add the note after creation?

**Comment by muianelson** [comment] 2016-02-11 05:22
it does not work without a note

I, [2016-02-11T08:19:07.213847 #3936]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"eMDlRNFkSIDaFtI83RNYgndn6844R9StichIqi9qr/g=", "default_project_name"=>"", "default_context_name"=>"Network and Infrastructure", "new_todo_starred"=>"false", "todo"=>{"description"=>"network", "notes"=>"", "due"=>"18/02/2016", "show_from"=>"12/02/2016"}, "project_name"=>"Network redesign", "context_name"=>"Network and Infrastructure", "initial_tag_list"=>"", "tag_list"=>"starred", "predecessor_input"=>"", "predecessor_list"=>"", "_source_view"=>"todo", "_group_view_by"=>"context", "_tag_name"=>""}
I, [2016-02-11T08:19:07.229465 #3936]  INFO -- : Completed 500 Internal Server Error in 16ms (ActiveRecord: 0.0ms)
F, [2016-02-11T08:19:07.229465 #3936] FATAL -- : 
ArgumentError (bad value for range):
  lib/tracks/utils.rb:39:in `textile'
  lib/tracks/utils.rb:26:in `render_text'
  app/models/todo.rb:382:in `render_note'
  app/controllers/todos_controller.rb:97:in `create'

**Comment by muianelson** [comment] 2016-02-11 05:25
screenshot of ui

![pic](https://cloud.githubusercontent.com/assets/6195150/12969959/0fb410ee-d099-11e5-8304-0e0d51d0672e.PNG)

**Comment by C-Otto** [comment] 2016-02-11 10:29
I can't reproduce this. Could you tell us something about the environment? Ruby version? How did you install? What's the OS?

**Comment by muianelson** [comment] 2016-02-11 14:09
The OS details are as follows:

![image](https://cloud.githubusercontent.com/assets/6195150/12978302/32545990-d0e1-11e5-9727-d12897b2f776.png)

I downloaded the software from bitnami tracks and ran the software .Please find the link below
https://downloads.bitnami.com/files/stacks/tracks/2.3.0-5/bitnami-tracks-2.3.0-5-windows-installer.exe

m not sure about the ruby version, how can i check?

**Comment by muianelson** [comment] 2016-02-19 10:44
any feedback?

**Comment by mattr-** [comment] 2016-02-19 20:32
It would seem this is a Windows specific issue? Does Bitnami's support pages have anything on this error, since they put the installation together?

**Comment by wfouche** [comment] 2016-04-08 11:45
https://community.bitnami.com/t/bitnamic-tracks-2-3-0-5-windows-not-working/41090

**Comment by mattr-** [comment] 2016-04-11 13:16
Since this seems to be a windows-specific issue (?), I'll close this for now. If there's something we need to do to the Tracks code to make this work, I'm happy to reopen this and look at it again, provided we can get some additional logs or more details on how to debug.

**Closed by mattr-** 2016-04-11 13:16 UTC
