### ISSUE TITLE
Tracks is not allowing default context to be changed to blank

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#1058] opened 2014-06-25 16:04 UTC
_Migrated from the original issue at https://www.assembla.com/spaces/tracks-tickets/tickets/1058_

from #1001:

Tracks is not allowing such a default context to be changed to blank. It gets reset to the originally defined, first letter capitalised context.

_Originally reported by lrbalt on August 8, 2010 at 08:44:50 (+0000)_

**Comment by ZeiP** [comment] 2019-05-21 12:57
I was unable to reproduce this with the most recent VCS version. Closing as fixed, feel free to open a new issue if the problem re-occurs.

**Closed by ZeiP** 2019-05-21 12:57 UTC
Labels: bug 🐛
