### ISSUE TITLE
Popups sometimes unusable

### ISSUE THREAD

**Issue by C-Otto** [TracksApp/tracks#1752] opened 2015-02-02 10:40 UTC
Both in Firefox and Chrome the popups (next to a task containing delete/defer/make project, or at the top when hovering over "Organize") sometimes are broken. When this is the case, I see gaps between the individual items and moving the mouse over the items and gaps often closes the popup. With this it is not possible to select certain items in the popup. Being quick sometimes help, but this is really annoying.

**Comment by tmueller78** [comment] 2015-02-02 10:44
Just as a comment: I've worked around this by selecting another task and then reselecting the task where the problem occurred. That most of the time helps, if not I do a reload of the page.
I agree that it is annoying when it happens, but it's not often the case for me (Chrome on Mac).

**Comment by dnrce** [comment] 2015-02-03 00:32
Duplicate of #1732

**Closed by dnrce** 2015-02-03 00:32 UTC
