### ISSUE TITLE
Mobile: date picker(s) could be better

### ISSUE THREAD

**Issue by GregSutcliffe** [TracksApp/tracks#2475] opened 2020-09-03 09:36 UTC
Not the best title, but there's two possible paths :)

Currently you have to fill in the day, month, and year separately when adding a due-date or show-from:

<img src="https://user-images.githubusercontent.com/827786/92098398-138a4d00-edd1-11ea-90c8-b9eb77f58ec8.png" width="250" height="200" />

If you fail to fill out any of the three, the date is not added. That's *super* annoying, as most due-dates are near-future.

The right fix is to use a mobile-suitable date-picker. I have no idea how to do that :P. What I could probably write a patch for is to have the controller assume values from $today if blank. So if I fill in "7" for the day, the code then fills in "September" and "2020". Thoughts?

**Comment by ZeiP** [comment] 2020-09-06 13:14
I'm a bit hesitant on assuming any values not given by the user and shown to them before saving. IMO an acceptable alternative to using an actual mobile-suitable date-picker (which of course would be preferable) would be auto-filling the month and year based on the current date on the UI side – so that the user can fix those if they're incorrect.

**Comment by GregSutcliffe** [comment] 2020-09-08 09:19
That's fair, I just have no idea about the mobile rendering. Auto-fill on render is risky, if you don't *clear* it you get a due date for *every* todo. The current code will not set a date unless all 3 fields are filled in (i.e. its using AND), I was proposing to move it to OR so that setting even one will do it (making assumptions ofc). But I take your point about not confirming things - especially with show-from where the todo will be immediately hidden.

It's starting to annoy me though, so I may have to scratch my own itch at some point. Time to break out the mobile docs, I guess :)

**Comment by ZeiP** [comment] 2021-08-30 20:15
Just noticed this is actually a duplicate of #1358, so closing this one. I certainly agree it's something to be fixed (and has been for a while apparently...) :)

**Closed by ZeiP** 2021-08-30 20:15 UTC
Labels: User interface, Enhancement ⚡️, help wanted
