### ISSUE TITLE
superclass mismatch for class Command during installation

### ISSUE THREAD

**Issue by Xeno19** [TracksApp/tracks#2575] opened 2021-02-01 15:04 UTC
Hi,

I try to install getontracks. But I get the following error when I exexute bundle exec rake db:migrate RAILS_ENV=production

rake aborted!
TypeError: superclass mismatch for class Command
/var/lib/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:2:in `<class:Thor>'
/var/lib/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:1:in `<top (required)>'
/var/lib/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:1:in `require_relative'
/var/lib/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:1:in `<top (required)>'
/var/lib/gems/2.7.0/gems/thor-1.0.1/lib/thor/group.rb:1:in `require_relative'
/var/lib/gems/2.7.0/gems/thor-1.0.1/lib/thor/group.rb:1:in `<top (required)>'
/var/lib/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `require'
/var/lib/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `block in require'
/var/lib/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:291:in `load_dependency'
/var/lib/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `require'
/var/lib/gems/2.7.0/gems/railties-6.0.3.3/lib/rails/generators.rb:6:in `<top (required)>'
/var/lib/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `require'
/var/lib/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `block in require'
/var/lib/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:291:in `load_dependency'
/var/lib/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `require'
/var/lib/gems/2.7.0/gems/coffee-rails-5.0.0/lib/coffee/rails/engine.rb:2:in `<top (required)>'
/var/lib/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `require'
/var/lib/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `block in require'
/var/lib/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:291:in `load_dependency'
/var/lib/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `require'
/var/lib/gems/2.7.0/gems/coffee-rails-5.0.0/lib/coffee-rails.rb:2:in `<top (required)>'
/usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `require'
/usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
/usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `each'
/usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `block in require'
/usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `each'
/usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `require'
/usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
/root/getontracks/tracks-2.5.1/config/application.rb:7:in `<top (required)>'
/root/getontracks/tracks-2.5.1/Rakefile:4:in `require'
/root/getontracks/tracks-2.5.1/Rakefile:4:in `<top (required)>'
/usr/share/rubygems-integration/all/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)

I try to install on latest Ubuntu (20.04) 

Any ideas?
Timo

**Comment by ZeiP** [comment] 2021-02-08 23:20
This seems to be caused by the Ubuntu/Debian package: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=955405 and https://bugs.launchpad.net/ubuntu/+source/ruby-thor/+bug/1885424 . I don't really have any instructions on how to overcome the issue, but an easy solution would be to use the Docker-based installation instead of the custom Ruby installation.

As this doesn't seem to be an issue with Tracks but rather the environment, I'll close the issue for now. Feel free to comment if you find out it's related to Tracks or there's something that should be done differently.

**Closed by ZeiP** 2021-02-08 23:20 UTC
Labels: Support
