### ISSUE TITLE
master: Unable to create todos

### ISSUE THREAD

**Issue by C-Otto** [TracksApp/tracks#1982] opened 2016-02-02 13:58 UTC
I'm running the latest master (with #1981). I am able to create ONE todo, but creating a second todo in the same project fails.

Popup: "New Context @Something will be also created. Are you sure?"
Error Message: There was an error retrieving from server: parsererror

Reloading the page or navigating to the project again does not help. Logging out and logging back in helps.

I don't have access to the logs now, will update when necessary (note to self: 14:57:00, project 272).

**Comment by mattr-** [comment] 2016-02-02 16:18
I'm not sure that it makes sense for us to do anything about this issue right now. If you can confirm that it happens without the code from #1981 merged in, then we can look further, but for now, I'll close this, since #1981 hasn't landed in master yet.

**Comment by C-Otto** [comment] 2016-02-02 18:26
@mattr- It was more a personal note, and I'm in the process of investigating further now.

This is what I see after the POST returns with 200, at the time when I press the `Add action` button for the second todo:
```
I, [2016-02-02T19:22:12.500288 #4122]  INFO -- : Started GET "/tracks/contexts.autocomplete?[object%20Object]&term=@XXX" for 1.2.3.4 at 2016-02-02 19:22:12 +0100
I, [2016-02-02T19:22:12.502940 #4122]  INFO -- : Processing by ContextsController#index as AUTOCOMPLETE
I, [2016-02-02T19:22:12.503021 #4122]  INFO -- :   Parameters: {"object Object"=>nil, "term"=>"@XXX"}
I, [2016-02-02T19:22:12.512583 #4122]  INFO -- :   Rendered text template (0.0ms)
I, [2016-02-02T19:22:12.512820 #4122]  INFO -- : Completed 200 OK in 10ms (Views: 0.6ms | ActiveRecord: 1.5ms)
```

This also happens on the clean current master branch (7300e3bf809eb2e650aed77a190e1210d577e3dc).

Please reopen.

I suspect a UI issue, as nothing in the log indicate creation of a todo.

**Comment by mattr-** [comment] 2016-02-02 20:12
Thanks for reproducing on master. Reopening.

**Comment by C-Otto** [comment] 2016-02-05 21:24
According to a git bisect, 461b328402ec72c9a866b6b3cd098565ea9b0609 is to blame. Now this is something I need to think about...

By the way, I can only trigger this in production mode.

**Comment by C-Otto** [comment] 2016-02-05 22:24
This is very hard to track down, bisecting for an hour did not give me anything helpful. However, it seems I can only reproduce this with Google Chrome (also on my Android phone), but not Mozilla Firefox.

**Comment by C-Otto** [comment] 2016-02-05 22:31
I can only reproduce this in production mode.

**Comment by C-Otto** [comment] 2016-02-05 22:41
Before creating a new todo, there is a check (using autocompletion) if the context already exists. It seems the second request (and every request after that) replies with HTTP status 304 ("Not Modified").

**Comment by C-Otto** [comment] 2016-02-05 23:16
It seems Google Chrome lately changed so that a response code of 304 does not result in status 200 (with the cached content) visible to the JavaScript code. When disabling caching in the request (`params.cache = false`), Chrome does not send the `If-None-Match` header and a standard HTTP 200 is received.

**Closed** 2016-02-09 22:05 UTC
