### ISSUE TITLE
Move complete project to another context

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#1592] opened 2014-06-25 16:19 UTC
_Migrated from the original issue #125 at https://www.assembla.com/spaces/tracks-tickets/tickets/125_

It would be nice if i could move a complete project on to another context. Sometimes i park a complete project in Someday/Maybe (see also [#114]), and if this become active i would like to change the Context of all associated Actions.

_Originally reported by Anonymous on September 9, 2005 at 11:58:20 (+0200)_

**Comment by ZeiP** [comment] 2019-05-21 13:01
Closing this as a duplicate of #773.

**Closed by ZeiP** 2019-05-21 13:01 UTC
