### ISSUE TITLE
ActionDispatch::Cookies::CookieOverflow (ActionDispatch::Cookies::CookieOverflow)

### ISSUE THREAD

**Issue by sealne** [TracksApp/tracks#1897] opened 2015-07-14 05:36 UTC
During account creation including the initial admin user the following error is given

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

and in the logs:

I, [2015-07-14T06:21:21.659416 #29999]  INFO -- : Started GET "/signup" for XX.XX.XX.XX at 2015-07-14 06:21:21 +0100
I, [2015-07-14T06:21:21.663581 #29999]  INFO -- : Processing by UsersController#new as HTML
I, [2015-07-14T06:21:21.678317 #29999]  INFO -- :   Rendered shared/_flash.html.erb (0.2ms)
I, [2015-07-14T06:21:21.681624 #29999]  INFO -- :   Rendered users/new.html.erb within layouts/login (5.1ms)
I, [2015-07-14T06:21:21.685693 #29999]  INFO -- :   Rendered shared/_footer.html.erb (2.1ms)
I, [2015-07-14T06:21:21.686656 #29999]  INFO -- : Completed 200 OK in 23ms (Views: 11.0ms | ActiveRecord: 1.5ms)
I, [2015-07-14T06:21:34.780961 #29999]  INFO -- : Started POST "/users" for XX.XX.XX.XX at 2015-07-14 06:21:34 +0100
I, [2015-07-14T06:21:34.787237 #29999]  INFO -- : Processing by UsersController#create as HTML
I, [2015-07-14T06:21:34.787792 #29999]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"YYYYYYYY", "user"=>{"login"=>"ab", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}}
I, [2015-07-14T06:21:34.807913 #29999]  INFO -- : Redirected to https://tracks.example.org/signup
I, [2015-07-14T06:21:34.808495 #29999]  INFO -- : Completed 302 Found in 20ms (ActiveRecord: 2.3ms)
F, [2015-07-14T06:21:34.814449 #29999] FATAL -- : 
ActionDispatch::Cookies::CookieOverflow (ActionDispatch::Cookies::CookieOverflow):
  actionpack (4.1.11) lib/action_dispatch/middleware/cookies.rb:531:in `[]='
  actionpack (4.1.11) lib/action_dispatch/middleware/session/cookie_store.rb:110:in`set_cookie'
  rack (1.5.4) lib/rack/session/abstract/id.rb:350:in `commit_session'
  rack (1.5.4) lib/rack/session/abstract/id.rb:226:in`context'
  rack (1.5.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.11) lib/action_dispatch/middleware/cookies.rb:562:in`call'
  activerecord (4.1.11) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.11) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in`call'
  actionpack (4.1.11) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.11) lib/active_support/callbacks.rb:82:in`run_callbacks'
  actionpack (4.1.11) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.11) lib/action_dispatch/middleware/remote_ip.rb:76:in`call'
  actionpack (4.1.11) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.11) lib/action_dispatch/middleware/show_exceptions.rb:30:in`call'
  railties (4.1.11) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.11) lib/rails/rack/logger.rb:20:in`block in call'
  activesupport (4.1.11) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.11) lib/active_support/tagged_logging.rb:26:in`tagged'
  activesupport (4.1.11) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.11) lib/rails/rack/logger.rb:20:in`call'
  actionpack (4.1.11) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.4) lib/rack/methodoverride.rb:21:in`call'
  rack (1.5.4) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.11) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in`call'
  rack (1.5.4) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.11) lib/rails/engine.rb:514:in`call'
  railties (4.1.11) lib/rails/application.rb:144:in `call'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:94:in`process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in`main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:111:in`block in create_thread_and_abort_on_exception'

This occurs if the username is less than 3 characters or it seems the password is less than 8.

I could see the logic for wanting a decent length password, but in that case a proper error should be displayed. However it shouldn't matter how long your username is.

**Comment by ZeiP** [comment] 2019-05-21 23:41
Closing as duplicate of #1985.

**Closed by ZeiP** 2019-05-21 23:41 UTC

**Comment by C-Otto** [comment] 2019-05-22 08:03
Duplicate of #1984?

**Comment by ZeiP** [comment] 2019-05-22 08:57
Actually both. The last few chapters of the issue description mention the credentials constraints that are in #1985 and the actual error message is in #1984.
