### ISSUE TITLE
Dependant actions should propogate due dates

### ISSUE THREAD

**Issue by GregSutcliffe** [TracksApp/tracks#2474] opened 2020-09-03 09:03 UTC
Suppose you have "action A" and "action B". Action B has a due date, so the UI looks like:

- [ ] Action A
- [ ] "Due in 39 days" Action B

All good. But if you now make Action B depend on A, in the UI it looks like:

- [ ] Action A >
  - [ ] Action B

The due date has disappeared - you don't even see B in the Calendar view anymore. There's *no* reminder that *both* tasks will need to be done in the next 39 days.

I'm not sure how to implement this, logic-wise. Perhaps the simplest option is to use the nearest due date of all children in the UI when rendering tasks?

**Comment by GregSutcliffe** [comment] 2020-09-04 10:02
Actually, it is in the Calendar view, marked "Pending", so that's something. Still, the blocking task should probably be marked in some way.

**Comment by ZeiP** [comment] 2020-09-06 13:00
You're right, it's kinda funny that the due date isn't applied to also the tasks it's dependent on. IMO this should be done programmatically, ie. not by setting the due date on the dependent tasks in the model but instead just checking all tasks that depend on the task for earlier due dates.

**Comment by ZeiP** [comment] 2020-09-06 13:02
This actually looks like a duplicate of #2411, so closing this one.

**Closed by ZeiP** 2020-09-06 13:02 UTC
Labels: Enhancement ⚡️, help wanted
