### ISSUE TITLE
Umlaut in Project Description

### ISSUE THREAD

**Issue by the193rd** [TracksApp/tracks#1771] opened 2015-02-25 18:16 UTC
**Tracks v 2.3rc1**
I have noticed that umlaut-letters (like ä,ö,ü) in a Project description causes a faulty text for the description on the specific project page.

Here is a (bureaucratic) example:
![tracks_1](https://cloud.githubusercontent.com/assets/9086241/6377202/e52c8c28-bd22-11e4-8db0-e757d843473b.png)

if I replace the umlaut-letters with something nicer the result is fine:
![tracks_2](https://cloud.githubusercontent.com/assets/9086241/6377208/ee1069a4-bd22-11e4-9ccc-0ec647ff68dc.png)

**Comment by C-Otto** [comment] 2015-02-25 18:38
I can't reproduce this (Apache, Linux, somewhat recent HEAD).

**Comment by dnrce** [comment] 2015-02-25 18:41
@C-Otto, the bug report is against 2.3.rc1, not master. Can you reproduce there?

**Comment by C-Otto** [comment] 2015-02-25 20:18
Tested on v2.3rc1, can't reproduce (Apache, Linux).

**Comment by the193rd** [comment] 2015-02-25 20:44
Okay, further information on my setup:
Debian Wheezy (ARM)
RVM for a ruby 2.2 environment
SQLite3
WEBrick

**Comment by C-Otto** [comment] 2015-02-25 21:22
Tested with WEBrick, can't reproduce.

**Comment by C-Otto** [comment] 2015-02-25 21:45
What does the logfile say? Mine:

`I, [2015-02-25T22:18:42.109766 #31758]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"SECRET", "_source_view"=>"project", "project"=>{"name"=>"Steuererklärung 2015", "description"=>"Steuererklärung 2015 machen", "state"=>"active", "default_context_name"=>"", "default_tags"=>""}, "wants_render"=>"true", "_group_view_by"=>"project", "_tag_name"=>"", "id"=>"1"}`

**Comment by C-Otto** [comment] 2015-02-25 21:47
`$ sqlite3 tracks-20-blank.sqlite3.db 'select * from projects';
1|Steuererklärung 2015|0|1|Steuererklärung 2015 machen|active|2015-02-25 20:14:31.305970|2015-02-25 21:18:42.133954||||`

**Comment by the193rd** [comment] 2015-02-26 11:40
In my log there is only something like:
`I, [2015-02-26T12:23:36.622043 #5391]  INFO -- :   Parameters: {"id"=>"7"}`
if I open the projectpage. Might be a dumb question: but should I run tracks in development mode (currently production) for a more detailed log like yours?

The database seems to be correct:
`$ sqlite3 tracks 'select * from projects'`
[…]
`7|Steuererklärung|9|1|24.02.2015 Steuererklärung für 2015|active|2015-02-24 18:19:33.815621|2015-02-26 1:11:56.281857|9||finanzen|2015-02-25 16:24:41.798155`
[…]

Which is reasonable, because the complete and correct text is changeable when I edit the project-description.

**Comment by C-Otto** [comment] 2015-02-26 12:01
For the log file entry, you need to change the project description (causing a PUT request in the log file, with the payload of the change).

**Comment by the193rd** [comment] 2015-02-26 12:53
Thanks. Here the output:
`I, [2015-02-26T13:49:44.944781 #5391]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"vOMUtAU5F5QoX1mQjq+8Z0/ECXDwQBQu61oOju4Mzus=", "_source_view"=>"project", "project"=>{"name"=>"Steuererklärung", "description"=>"24.02.2015\nSteuererklärung für 2015", "state"=>"active", "default_context_name"=>"Organisation", "default_tags"=>"finanzen"}, "wants_render"=>"true", "_group_view_by"=>"project", "_tag_name"=>"", "id"=>"7"}`

The text is correct in the Project Settings Description-Box. Just the displayed text is wrong.

**Comment by C-Otto** [comment] 2015-02-26 13:14
Hm, I must admit I have no real clue, but my gut feeling is that the frontend/browser is to blame. Could you try using another browser? Check the language and locale settings in the browser? Run the browser in safe mode without plugins?

PS: I also tried adding a line break in the description, I still can't reproduce the problem.

**Comment by the193rd** [comment] 2015-02-26 14:28
I've already tried it with Chromium, Opera and Firefox. Everywhere the same.

**Comment by dnrce** [comment] 2015-03-09 01:32
@the193rd, what is your system locale (`echo $LANG`)? Also, can you please share the contents of your `database.yml` (with passwords and hostnames sanitized, of course)?

**Comment by the193rd** [comment] 2015-03-09 15:28
```
$ locale
LANG=de_DE.UTF-8
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

```
$ cat database.yml
development:
  adapter: sqlite3 
  #adapter: mysql2
  database: tracks
  # set this if you are storing utf8 in your mysql database to handle strings
  # like "Réné". Not needed for sqlite. For PostgreSQL use encoding: unicode
  # encoding: utf8
  #host: localhost

production:
  adapter: sqlite3 
  database: tracks
  # set this if you are storing utf8 in your mysql database to handle strings
  # like "Réné".Not needed for sqlite. For PostgreSQL use encoding: unicode
  # encoding: utf8
  #host: localhost

# The following is an example to configure Tracks to use sqlite

#production:
#  adapter: sqlite3
#  database: db/tracks-20-blank.sqlite3.db
#  pool: 5
#  timeout: 5000


# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test: &TEST
  adapter: sqlite3 
  database: tracks_test
  encoding: utf8

cucumber:
  <<: *TEST
```
I removed the username/password parts

**Comment by C-Otto** [comment] 2015-03-10 06:46
For comparison, this is what I use on my server (where everything works as expected):

```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.utf8
LC_TIME=de_DE.utf8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.utf8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=de_DE.utf8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by dnrce** [comment] 2015-03-13 04:46
@the193rd, could you perhaps post a gist of the HTML source of the page that isn't displaying correctly? I'm not able to reproduce this, and while the screenshots are helpful to illustrate the problem, they don't provide much information to troubleshoot. Thanks!

**Comment by the193rd** [comment] 2015-03-13 09:03
@dnrce  of course!
https://gist.github.com/the193rd/75d42102e4a61722354d
(I deleted the parts about other projects, tags and context - do you think they might be important?)
The missing Text appears in line 130. It should be ”Dies ist ein ästhetischer Test mit öffentlichem gist.“

Btw. I noticed, that the problem also occurs in the drop-down notebox for some action. Should be related.
If I edit the note/Description the full text is still available.

**Comment by C-Otto** [comment] 2015-03-13 09:06
`<div class="project_description"><p>Dies ist ein</p></div>`

So the space before the umlaut also is removed...

**Comment by dnrce** [comment] 2015-04-12 20:40
@the193rd, could you possibly test with Tracks 2.2? I'd like to know whether what you're seeing is a regression.

**Comment by lrbalt** [comment] 2015-04-13 14:32
Could you enable utf8 in your database.yml too? See the comment on the encoding attribute

**Comment by the193rd** [comment] 2015-04-17 07:33
Sorry for the delay, I’ll try to find the time for further tests this weekend. :)

**Comment by dnrce** [comment] 2015-04-18 00:43
I'm unable to reproduce this with 2.3_branch @556c68c2e61ca0e504a33213435fcb6fdbeece80 in a Ubuntu 14.04.1 VM using RVM Ruby 2.2.1 and with locale set to the following:
```
$ locale
LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES=POSIX
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

**Comment by matjack1** [comment] 2015-04-22 21:17
I'm on a similar system, Ruby 2.2.0 on Ubuntu 14.04 and I cannot reproduce the bug. I've the same database.yml and everything works fine.

@lrbalt was suggesting to enable utf-8, but actually the comment says also that is not needed for sqlite, and I confirm that.

Btw, I use accent quite often in Tracks on my installation (with PostgreSQL) and everything works fine.

**Comment by dnrce** [comment] 2015-05-02 19:17
Given our inability to reproduce this I'm willing to close it. Any objections?

**Comment by dnrce** [comment] 2015-05-15 01:31
No objections voiced.

**Closed by dnrce** 2015-05-15 01:31 UTC
