### ISSUE TITLE
Do assignment of responsible persons

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#1516] opened 2014-06-25 16:18 UTC
_Migrated from the original issue #49 at https://www.assembla.com/spaces/tracks-tickets/tickets/49_

It will be convenient to do assignment of responsible persons for task

_Originally reported by Anonymous on April 4, 2005 at 07:29:31 (-0500)_

**Comment by ZeiP** [comment] 2019-05-21 23:16
Closing as duplicate of #527

**Closed by ZeiP** 2019-05-21 23:16 UTC
Labels: multi-user
