### ISSUE TITLE
When should rendering take place?

### ISSUE THREAD

**Issue by jyruzicka** [TracksApp/tracks#1773] opened 2015-02-28 18:45 UTC
Was about to start work on a minor fork that added markdown support, when I noticed that rendering (via Tracks::Utils) appears to take place in a couple of different places:

* In most cases, rendering occurs between the model and the view
* However, a todo's notes are saved to the database rendered as rendered_notes (even though the notes themselves are stored un-rendered)

Is this a deliberate decision, or just one of those things that happens on a project? If the second, I can start poking away at perhaps making it more uniform...

**Comment by C-Otto** [comment] 2015-02-28 18:48
12d8915eda82cd73478d99e49d67005451d3e70e looks like a quick fix to me.

**Comment by dnrce** [comment] 2015-02-28 23:34
Which rendering are you referring to? The notes, specifically?

Notes are rendered on save, when it's only one note being touched, so they do not have to be rendered in bulk at view time. It's entirely for performance reasons.

We're always happy to receive improvements.

**Comment by jyruzicka** [comment] 2015-03-02 08:03
> We're always happy to receive improvements.

It's mainly whether or not you consider it an improvement :stuck_out_tongue: 

I'll have a think about setting up some sort of benchmark and testing how much time it takes to render, say, 100 notes at a stretch. If it turns out it's only saving 0.1s or whatever, I'll see about centralising it and pass it into you via pull request, how's that sound?

**Comment by dnrce** [comment] 2015-03-03 02:17
Sounds good.

**Comment by dnrce** [comment] 2015-03-03 02:18
I'm going to close this issue because it's a question and not a bug or feature request. We can discuss anything further in a pull request or on the mailing list.

**Closed by dnrce** 2015-03-03 02:18 UTC

**Comment by lrbalt** [comment] 2015-03-06 10:31
sorry for commenting after the fact...

The rendered notes in the database are a performance fix. Before the new fragment caching of rails, every page load caused all notes to be rendered using markdown. If you have a lot of notes with markup, loading a page could take a long time

Since we now use fragment caching, there is no need anymore to pre-render the notes and save them in the db. This form of do-it-yourself caching could be removed. Although at the time I was rather proud of the simple fix :-)
