### ISSUE TITLE
Dependency on Git and fetching using unecrypted protocol

### ISSUE THREAD

**Issue by habernal** [TracksApp/tracks#2631] opened 2021-07-31 12:30 UTC
Trying to install Tracks 2.5.1 from scratch in a fresh test environment (Ubuntu 20.04), I've noticed the following:

```plain
$ bundle install
The git source `git://github.com/ZeiP/chartjs-ror.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config set --local git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Following files may not be writable, so sudo is needed:
  /usr/local/bin
  /var/lib/gems/2.7.0
  /var/lib/gems/2.7.0/build_info
  /var/lib/gems/2.7.0/cache
  /var/lib/gems/2.7.0/doc
  /var/lib/gems/2.7.0/extensions
  /var/lib/gems/2.7.0/gems
  /var/lib/gems/2.7.0/specifications
You need to install git to be able to use gems from git repositories. For help installing git, please refer to GitHub's tutorial at https://help.github.com/articles/set-up-git
```

What is `git://github.com/ZeiP/chartjs-ror.git` and why is it being fetched through git?

**Comment by ZeiP** [comment] 2021-08-08 21:35
Sorry for the delay, I've been too busy with other things since the start of July! 

That's a fixed version of the chartjs-ror library which contains a wrapper element and makes the library work properly. If my memory serves me right the upstream is abandoned, so the fix hasn't been merged in; the stats page relies heavily on this. 

Because there is an upstream, it's also available as an ”official” gem and therefore the required version is fetched through Git. I have to admit I didn't think of the Git dependency being caused by this; not sure if that's something we could avoid in a sensible way. I'll take a look at this; feel free to suggest if you have some solutions in mind.

**Comment by habernal** [comment] 2021-08-09 06:47
Ruby and their libraries is a complete alien world to me. But generally: If the library is a fork of an abandoned project, a clean solution would be to rename it in your repo (chartjs-ror2 or similar), publish in the ruby repository (no idea how easy/hard that is), and link the new official release as a dependency.

**Closed** 2021-08-25 14:32 UTC
Labels: bug 🐛, Development
