### ISSUE TITLE
Note written in Korean character does not shown.

### ISSUE THREAD

**Issue by let-alone** [TracksApp/tracks#2159] opened 2018-12-06 05:02 UTC
I use Tracks on raspberian( raspberry pi OS)
It works properly.

But There seems to be one problem.

My native language is Korean.

Korean characters use utf-8 character encoding.

There was no difficulty in entering Korean characters  on Description,Notes,Project etcs.. 

Korean characters appeared well in Description,Project etcs...

but when I try to see the note with click on small note icon (which show in end of description) 

I can not see the note written in Korean character. but note written in only Alphabets and numbers  reveals well

How can I see the note written in Korea character  properly with click on small note icon 

![3](https://user-images.githubusercontent.com/45648610/49562509-315a2200-f95f-11e8-942c-78d0310eb34a.png)

![2](https://user-images.githubusercontent.com/45648610/49562499-2bfcd780-f95f-11e8-984b-fc7fe4ebb069.png)

**Comment by matjack1** [comment] 2018-12-06 19:36
@let-alone I cannot reproduce your problem on my setup:

![image](https://user-images.githubusercontent.com/65402/49607536-81a0a680-f996-11e8-9199-da1e4415c7a9.png)

is this what is broken on your issue? It seems working fine here. Is it maybe something related to your database? I'm using MySQL and you?

**Comment by let-alone** [comment] 2018-12-07 06:20
thanks for reading of my issue.

saddly 
" 이게 한국인이야?" -> this part does not shown in my Tracks.

I use MySQL instead of  SQLite3.

My step by step procedure of installation Tracks is the same as the on below

There is no error message on the way of installation

Tracks works  well ,except of Note written in Korean character does not shown.

I donnot know what is wrong.


____________________




My step by step procedure of installation Tracks on raspberry pi 





sudo apt-get update  # for update of raspberry pi OS

sudo apt-get upgrade # for upgrade of raspberry pi OS

sudo apt-get install fonts-unfonts-core ibus-hangul ibus # for use Korean character on system.

mkdir Tracks

cd Tracks/

wget https://github.com/TracksApp/tracks/archive/v2.3.0.zip

unzip v2.3.0.zip

cd tracks-2.3.0/

sudo apt-get install mysql-server mysql-client  # for installation of mysql server

sudo mysql -uroot

 

#After I connected to mysql server

CREATE DATABASE tracks DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci; # Let MySQL database tracks  use utf8 

create user 'pi'@'localhost' identified by 'raspberry';

GRANT ALL PRIVILEGES ON tracks.* TO pi@localhost IDENTIFIED BY 'raspberry' WITH GRANT OPTION;

quit   # for discconection of mysql

 

sudo gem install bundler

cp Gemfile Gemfile.backup

nano Gemfile

# add # in front of sqlite3 for unactivating sqlite3 


nano editor quit

  

sudo apt-get install ruby2.3-dev

sudo apt-get install default-libmysqlclient-dev

bundle install --without development,test

sudo apt-get autoremove

cd config/

cp database.yml.tmpl database.yml

cp site.yml.tmpl site.yml

 

 

**************

Open the file config/database.yml and edit the production: section with the details of your database. If you are using MySQL the adapter: line should read adapter: mysql2, host: localhost (in the majority of cases), and your username and password should match those you assigned when you created the database. If you are using SQLite3, you should have only two lines under the production section: adapter: sqlite3 and database: db/tracks.db.

***************

 

 

nano database.yml

 

=>여기서 adapter: mysql2, host: localhost  your username and password should match those you assigned when you created the database



bundle exec rake time:zones:local

nano site.yml

 

=>여기서 

******************

Open the file config/site.yml, and read through the settings to make sure that they suit your setup. In most cases, all you need to change are the salt: "change-me" line (change the string “change-me” to some other string of your choice), the administrator email address (admin_email), and the time zone setting. For the time zone setting you can use the command bundle exec rake time:zones:local to see all available timezones on your machine

******************

 

 

cd environments/

cp production.rb production.rb.backup

nano production.rb

 

=>여기서

******************

If you intend to deploy Tracks with the built in webserver called WEBrick, you’ll need to change config.serve_static_assets to true in config/environments/production.rb in order for the images, stylesheets, and javascript files to be served correctly.

******************

 

 

cd ..

cd ..

# twice of cd.. -> for change route to tracks root directory 

bundle exec rake db:migrate RAILS_ENV=production

bundle exec rake assets:precompile RAILS_ENV=production

bundle exec rails server -e production

 

*****************

Visit http://0.0.0.0:3000/signup in a browser (or whatever URL and port was reported when you started the server in the step above) and chose a user name and password for admin user. O

*****************

 

___________________________________________

**Comment by C-Otto** [comment] 2018-12-07 07:59
Could you have a look at the log file in `(tracks directory)/log/production.log`? Please create a new task with a Korean note. Then try to see that note in the UI. Please attach the log files (starting from the time when you created the new task/note).

**Comment by let-alone** [comment] 2018-12-08 19:31
Thanks for reading

there is two log in below..

First.
I create "for demo" with note "for demo" in "in box" Contexts in mobile mode
and I try to view note with click small note icon

-> it works correctly.( I can see the note when I click the small note icon)


Second.
I create "Github에 보낼 예제" with note "Github에 보낼 예제"  in " in box" Contexts in mobile mode
and I try to view note with click small note icon

-> it works partial...( I can see the note only "Github" .          "에 보낼 예제" -> doesnot shown. ( captured image attached)

I find out something
1) note with all alphabet -> I can see the whole note when I click the small note icon
2) note with start alphabet -> I can see the note only first alphabet part, I cannot see written with korean language part and part of the alphabet behind korean language part. when I click the small note icon( for example note "Github에 보낼 예제. it is the samle for github"  I can see the note only "Github"( first alphabet part only)
3) note with start korean language -> I cannot see the whole note when I click the small note icon, only blank shown

thanks for help.
thanks.
[log_alphabet.log](https://github.com/TracksApp/tracks/files/2659991/log_alphabet.log)
[log_korean.log](https://github.com/TracksApp/tracks/files/2659992/log_korean.log)
![img_6538](https://user-images.githubusercontent.com/45648610/49689856-c8df9080-fb6a-11e8-80be-c44a258ab92f.PNG)

**Comment by C-Otto** [comment] 2018-12-09 12:02
Thank you for the information! Which version are you running?

**Comment by let-alone** [comment] 2018-12-09 19:08
Thanks for reading 

I use v 2.3.0
I get the file from https://github.com/TracksApp/tracks/archive/v2.3.0.zip

**Comment by C-Otto** [comment] 2018-12-09 19:21
OK, that was my guess. I am unable to reproduce the issue with v2.3.0 on my laptop, and I can't see where things could be broken.

You can try to edit the file `lib/tracks/utils.rb`. In there you find `def self.render_text(text)` with several lines starting with `rendered = ` below. I suggest you try the following:

1) Add `rendered = text` before the three `rendered =` lines
2) Replace `auto_link_message(text)` by `auto_link_message(rendered`)

Then you can try to disable the three (original) lines starting with `rendered =` by replacing them with `#rendered =` (adding a `#` at the front). This will disable certain features (like clickable links) but we might be able to find where the bug is hiding:

For example you can try:

```
    def self.render_text(text)
      rendered = text
      #rendered = auto_link_message(rendered)
      rendered = textile(rendered)
      rendered = helpers.auto_link(rendered, :link => :urls)

      # add onenote and message protocols
```

Afterwards you should restart tracks and/or remove the caches by running `rake tmp:cache:clear` in the tracks installation directory.

**Comment by let-alone** [comment] 2018-12-10 00:07
Thanks you
I will try
But I am in office now.so it take a time to try (maybe over 1 day..)
I promise to write about the results of the trial here

**Comment by let-alone** [comment] 2018-12-10 22:09
Thanks for reading


in my original utils.rb

def self.render_text(text)
rendered = auto_link_message(text)
rendered = textile(rendered)
rendered = helpers.auto_link(rendered, :link => :urls)

I modified to

def self.render_text(text)
rendered = text
rendered = auto_link_message(rendered)
#rendered = auto_link_message(text)
#rendered = textile(rendered)
#rendered = helpers.auto_link(rendered, :link => :urls)

But I afraid ,I modified utils.rb correctly( because my modification doesnot match that your example..

I saved the modifed utils.rb
I quit tracks server( with Ctrl+C )
I ran "rake tmp:cache:clear"

after ran "rake tmp:cache:clear" message is below

pi@raspberrypi:~/Tracks/tracks-2.3.0 $ rake tmp:cache:clear
/usr/local/bin/rake:22:in `load': cannot load such file -- /usr/share/rubygems-integration/all/gems/rake-10.5.0/bin/rake (LoadError)
from /usr/local/bin/rake:22:in `<main>'

Hmm...I guess something wrong with my system.(LoadError)..


anyway..

I try to see note with click small note icon

It partial works..

I can see some notes written in korean characters that were not seen before.(captured image attached..)
but some notes written in korean characters doesnot shown still.

![tracks](https://user-images.githubusercontent.com/45648610/49764513-0717b400-fd13-11e8-834d-0c0f642d9fea.PNG)


I guess..
Because of the length of the sentence, it seems that there is a difference between being seen and not seen.
The notes written in korean characters I saw. they were short - length notes.
The notes written in korean characters that were not shown were relatively long notes.

I donot know my guess is correct or not


Oh... my guess is incorrect...

It doesnot matter the length of the sentence.

the note written in korean characters which created after modify the utils.rb
-> shown...

but
the note written in korean characters which created before modify the utils.rb
-> If short sentence ->shown corretly now
If long sentence -> does not shown yet..



Under the changed utils.rb, I will write another note(long sentence) and look at the log.

created note with korean character is seen well..

The log is presented as below



I, [2018-12-11T06:02:44.884575 #30829]  INFO -- : Started POST "/todos" for 192.168.1.108 at 2018-12-11 06:02:44 +0900
I, [2018-12-11T06:02:44.889280 #30829]  INFO -- : Processing by TodosController#create as JS
I, [2018-12-11T06:02:44.891346 #30829]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"8Db49zSHRGUyQMySspD4NlPzeNtg/YqhWBrqZS4PpRQ=", "default_project_name"=>"", "default_context_name"=>"in box", "new_todo_starred"=>"false", "todo"=>{"description"=>"티카타카111", "notes"=>"\n\n그 첫 번째 위반사항은, 삼성바이오로직스가 바이오젠사와 맺은 콜옵션에 대한 계약내용을 제대로 공시하지 않았다는 것이다.\n\n \n\n흔히들 재무제표 = 숫자 (재무상태표, 손익계산서 등)으로만 알고있는데, 실제로 더 큰 분량을 차지하는 것은 바로 주석이다. 재무제표의 주 목적이란 게 투자판단에 도움이 되기 위함인데, 숫자로 표현할 수 없거나 숫자 하 표기했을 때 오해가 생길 수 있는 부분을 설명하기 위해 존재하는 게 주석이다.\n\n \n\n바이오젠과의 콜옵션은 자회사로 존재하는 삼성바이오에피스의 지배구조를 바꿀만큼 중대한 내용을 담고 있는데, 이를 주석으로 공시하지 않았단 것은 삼성바이오로직스의 잘못이 맞다. 쉽게 말해, 콜옵션 내용대로라, 처음부터 삼성바이오에피스는 내꺼 아닌 내꺼 같은 썸을 타 관계회사로 처리하는 게 맞다. 재무제표상으론 마치 부부인냥 자회사로 올려놓고 그 속사정을 설명하지 않은 것이다. 그리고 이 관계가 바뀌었을 때, 재무제표에 얼마나 큰 (인위적인) 변화가 생겼는지는 지난글에서 살펴본 바 있다.\n\n여기까지가 “명백한 회계기준을 중대하게 위반”이라면, 이제 “고의”에 대한 이야기를 해보자.\n\n \n\n콜옵션에 대한 내용을 숨기, 삼성 바이오로직스가 삼성 바이오에피스를 자회사로 둔 이유는 무엇인가?\n\n \n\n결국 이게다 뽀록(Fluke) 한 방을 위해서다.\n\n \n\n삼성바이오로직스가 2015년에 공정가치 인식에 따라 거둔 막대한 이익은, 오로지, 연결회계를 지분법으로  때문에 가능했다. 만약, 삼성 바이오에피스를 원칙대로 지분 쭉 처리했었더라면? 애초에 이런 1회성 가치인식의 기회 따위는 없다.\n\n \n\n설령 이렇게 한 방에 1회성 이익을 땡길 기회 혹은 유혹이 있다고 하더라도, 이를 실제로 대놓고 실행에 옮기기에는 상당한 용기와 뻔뻔함이 필요하다. 하지만 역시 삼성이 하면 다르다.\n\n \n\n지난 11월 14일 증선위 발표에 다음과 같은 결론을 내렸다.\n\n \n\n“삼성바이오로직스가 2012년~2014년 자회사 삼성바이오에피스를 자회사로 분류한 것 ‘중과실’이며 2015년 회계기을 자의적으로 해석한 것은 ‘고의적’ 회계기준 위반”\n\n \n\n여기서 2015년 회계기준을 자의 해석했다는 것은, 삼성바이오에피스의 회계처리를 연결회계에서 지분법으로 변경한 것을 뜻한다. 원래부터 지분법으로 처 했었어야 하지만 (이를 어긴 것 자체가 중과실이다), 기존에 연결회계로 처리하던 것을, 콜옵션 실현 가능성이 올라갔다라는 이유만으로 지분법으로 변경하면서 막대한 평가 이익을 2015년에 땡긴 것은 고의적 회계기준 위반이라는 것이다.\n\n \n\n콜옵션의 실현 가능성의 변화만으로 지배력이 상실되었다 주장 자체가 일단 자의적이다. 콜옵션 계약이란 게 2012년부 쭉 있었던 건데, 해당 옵션의 행사 가능성의 변화 (말 그대로 가능성이기 때문에, 객관적일 수가 없다)만으로 자회사가 됐다가 관계회사가 됐다 하는 것은 삼성바이오에피스를 4조 5천억짜리 슈뢰딩거의 고양이쯤으로 만드는 짓이기 때문이다.\n 삼성바이오로직스가 순수하게 회계처리의 오류를 바로잡기 위해 지분법으로 고쳤다면, 꼭 2015년에 고쳐서 인위적으로 막 평가이익을 발생시킬 것이 아니라, 2012년부터 소급적용을 해서 쭉 관계회사로 뒀었어야 한다(그래야 증선위는 이게 맞는 회계처리였다고 판단한다). 다시 한 번 강조하지만, 이 평가 건 자회사를 관계회사로 변경할 때 그때 딱 한 번 밖에 발생 안된다. 즉, 2012년부터 관계회사로 처리를 했으면 2015년에 이런 몇 조짜리 뽀록성 평가이익이 생길 리는 없다. 하지만  주장은, 2014년까지는 때려죽여도 자회사였는데, 갑자기 2015년부터 관계회사가 되었다는 것이다. 그리고 그 근거란 것이 오로지 콜옵션의 행사 가능성 변화 때문이란다.\n\n \n\n이  작위적이고, 궁핍한 변명인가. 범죄스릴러 영화를 보는데 범(콜옵션)이 그동안 한 번도 영화에 등장하지 않은(제대로 공시되지 않은) 인물이란다. 근데 그 범인에겐 사실 출생의 비밀 있고(애초부터 자회사가 아니라 관계회사였다), 범인이 피해 죽인 이유(지분법으로 변경한 이유)또한 자기를 알아 본 사람이 아닐까 하는 의심(콜옵션의 행사 가능성) 때문이란다.\n\n \n\n전문적인 회계적인 지식이 없어도, 우리는 왜 이런 삼성류 삼류 각본이 실행되었는지에 대한 정답을 알고 있다.\n\n \n\n위에서 시켰거든. 이렇게 만들어진 뽀록이란 게, 보통 뽀록이 아니라 이재용에게 꼭 필요했던 쿠션을 잔뜩 맥인 필살 뽀록이었기 때문이다.\n\n \n\n이 뽀록 한 방은 1) 삼성 바이오로직스가 코스피에 상장을 가능하게 해줬고 (이런 뽀록 없 콜옵션 부채인식으로 인해 자본잠식 상태에 빠져있었다면, 자기자본 부족으로 상장이 불가능했을 것이다), 2) 삼성 바이오로직스의 값어치가 떡상했기 때문에 이를 소유한 제일모직은 갑자기 높은 성장 가능성이 있는 바이오기업을 거느린 기업으로 둔갑했으며, 3) 이는 삼성물산과 합병할 때 제일모직이 원하는 합병비율을 받도록 도와줬고, 4) 마지막으로 합병을 통 탄생된 기업의 대주주인 이재용은 (구)삼성물산이 보유한 삼 지분을 통해 삼성가의 알파이자 오메가인 삼성전자를 냠냠 할 수 있었다!\n아 물론, 이렇게 번거로운 방식대신, 그냥 이건희의 모든 지분을 상속세 내고 이재용에게 상속해 주는 간단 방법도 있기는 있었다. 이 쉬운 방법을 냅두고, 삼성바이오로직스의 회계를 분식해서 제일모직의 가치를 뻥튀기시키고, 이 합병을 밀어부치기 위해, 최순실 딸에게 말을 대줘서 국민연금까지 움직이는 아주 힘든 길을 선택한 것이다. 이 쉬운 방 이재용 부회장에게 제대로 알려주지 못한 책임자들은 모두 반성해야 된다. 그것도 졸라 많이.\n\n \n\n왜냐하면 니덜이 이 따위 짓을 벌인 탓에 삼성쪽에 붙어서 투표를 해준 국민연금이 몇 천 억을 날렸고, 삼성바이오로직스에 투자했던 개미들 잔뜩 피해를 봤거든. 삼성바이오로직스가 매매 중지가 됐든, 주가가 떡락을 하든, 이제 이재용에게 무슨 피해가 있을까?  제일모직은 삼성물산을 먹었고, 그 덕에 이재용은 원하던 삼 주식을 가져왔는데.\n\n \n\n지금의 비난은 일시적이지만, 이렇게 해서 굳힌 돈은 영원하다란 믿음이 없으면 절대 할 수가 없는 짓이다. 그러니까 우리나라 최대의 재벌이란 게 국민연금까지 끼고 이렇게 후진 방법을 선택한 것이다. 그리고 이렇게 불법적이고, 후진적인 방법이 용납될수록, 떳떳한 방법으 경쟁을 하는 사람만 빙신이 되기 마련이고, 이는 그 사회의  한 단계 낮아짐을 의미한다.\n\n \n\n글로벌 경쟁력? 세금 깎아준다고 갑자기 생기는 것도 아니고, 기업들이 원하는 대로 법 만들어 준다고 생기는 것도 아니다. 그 시장의 룰이 얼마 공정한 경쟁을 할 수 있도록 유도하고, 그리고 이 룰이 실제 얼마나 모두에게 공평하게 적용되는가에 따른 시스템 경쟁에 앞서나갈 때 비로소 글로벌 경쟁력이란 게 생겨난다.\n\n \n\n만약 미국 SEC가 이걸 분식회계라고 결론을 냈다면, 어떻게 했을까? 과징금은 몇 십 억이 아니라 최소 몇 조는 나왔을 거고, 관계자들 여럿 구속됐을 수 있다. 무엇보다도, 지금 삼성바이오로직스처럼 우리는 떳떳하다는 공지 걸고 행정 소송은 절~대 못한다. 그건 장담할 수 있다.\n\n \n\n물론, 이렇게  권위가 없는 것은, 스스로가 2015년에 회계분식 결론을 내고, 삼성물산 합병에 대한 별 다른 제동을 걸지 못한 탓이 크다. 당시 대통령을 떠올려 보면, 왠지 수긍이 가는 건 어쩔 수 , 앞으로 금융위가 존경받는 규제당국으로 거듭나려면, 정권과 무관하게 독립성과 공정성을 가진 집단으로 발전했으면 한다. 공무원은 연금이 아니라 자존심으로 하는 건데, 앞으로는  누가 오든 간에 분발해 주시라.\n\n \n\n이제 남은 것은 분식회계에 대한 처벌이다. 과연 이 사태로, 어느 선까지 얼마나 처벌을 받는지, 모두 관심을 갖자.\n", "due"=>"", "show_from"=>""}, "project_name"=>"", "context_name"=>"in box", "initial_tag_list"=>"", "tag_list"=>"", "predecessor_input"=>"", "predecessor_list"=>"", "_source_view"=>"context", "_group_view_by"=>"context", "_tag_name"=>""}
I, [2018-12-11T06:02:45.148812 #30829]  INFO -- : Read fragment views/todos/151-20181210210244944384688/20181211/context/false/c9a33e74913927d9ce9c62c2eadea771/c9a33e74913927d9ce9c62c2eadea771 (0.4ms)
I, [2018-12-11T06:02:45.184492 #30829]  INFO -- : Write fragment views/todos/151-20181210210244944384688/20181211/context/false/c9a33e74913927d9ce9c62c2eadea771/c9a33e74913927d9ce9c62c2eadea771 (2.4ms)
I, [2018-12-11T06:02:45.185047 #30829]  INFO -- :   Rendered todos/_todo.html.erb (38.2ms)
I, [2018-12-11T06:02:45.188181 #30829]  INFO -- :   Rendered todos/create.js.erb (50.0ms)
I, [2018-12-11T06:02:45.189140 #30829]  INFO -- : Completed 200 OK in 297ms (Views: 49.7ms | ActiveRecord: 143.1ms)

**Comment by C-Otto** [comment] 2018-12-11 07:54
OK, thank you for the information! I'm afraid I do not know much about Ruby/textile/..., maybe someone else can chime in? @dnrce @mattr-

**Comment by mattr-** [comment] 2018-12-11 13:33
I'm a conference currently, but I'll take a closer look into all of this after I return next week.

**Comment by let-alone** [comment] 2019-01-22 03:06
I'm sorry to bother you, but is there anyone who found a clue for this issue?

**Comment by ZeiP** [comment] 2020-09-06 15:00
@let-alone, I tried your example in my own MySQL-based installation. I first failed to add the task at all due to the table using latin1 instead of utf8 as character set. After I converted that per the instructions in https://stackoverflow.com/questions/105572/a-script-to-change-all-tables-and-fields-to-the-utf-8-bin-collation-in-mysql, I was able to view the note correctly.

I also released a new version which fixes a lot of things – not sure if there's anything specifically for this kind of an error, but I'd ask you to test with the new version and check the collation of your database & table & columns. If you're using the most recent release (either 2.5.0 or the master branch) and utf8 in your database and continue having any issues, please let me know by commenting to this issue and I'll re-open it.

Closing for now due to being unable to reproduce the error.

**Closed by ZeiP** 2020-09-06 15:00 UTC
Labels: Support
